steps:

    - name: gcr.io/kaniko-project/executor:latest
      args:
        - "--destination=${_IMAGE_URI}"
        - "--cache=true"
        - "--cache-ttl=504h"
        - "--dockerfile=./Dockerfile"
      timeout: 1200s
      id: Build and push image

    - name: gcr.io/cloud-builders/docker
      entrypoint: 'bash'
      args: 
        - "-c" 
        - "docker" 
        - "run" 
        - "--network=cloudbuild"
        - "-t" 
        - "${_IMAGE_URI}" 
        - "--file=./Dockerfile"
        - "."
        - "dbt run --select tag:daily && dbt test --select tag:daily && dbt docs generate"

timeout: 1800s
images:
    - "$_IMAGE_URI"
options:
    substitutionOption: ALLOW_LOOSE
    logging: CLOUD_LOGGING_ONLY
substitutions:
    _GCR_HOSTNAME: gcr.io
    _IMAGE_URI: "southamerica-east1-docker.pkg.dev/door2door-381302/dbt-door-2-door/dbt_app:lastest"
    _SERVICE_NAME: door2door-elt
    _SERVICE_ACCOUNT: door2door-381302@appspot.gserviceaccount.com
