# For more information on how to configure this file, please see:
# https://docs.getdbt.com/docs/profile

door2door_dbt: # this needs to match the profile: in your dbt_project.yml file
    target: local
    outputs:
        local:
            type: bigquery
            method: service-account
            project: "{{ env_var('DBT_PROJECT') }}"
            dataset: "{{ env_var('DBT_DEFAULT_DATASET') }}"
            threads: 4
            location: us-east4
            keyfile: "/Users/samuel/Documents/GitHub/door2door/credentials/door2door-381302-68f36cb5370c.json"
